{-# LANGUAGE OverloadedStrings #-}

-- belief.md writer.
-- This is the agent's sole deliverable per task — a structured Markdown
-- summary of everything the probe revealed.
module Blackbox.Belief
    ( writeBelief
    , renderBeliefMd
    ) where

import qualified Data.Text as T
import           Data.Text (Text)
import qualified Data.Text.IO as TIO
import           System.FilePath ((</>))

import           Blackbox.Types


-- Write belief.md to the task dir.
writeBelief :: FilePath -> Belief -> IO ()
writeBelief taskDir b = TIO.writeFile (taskDir </> "belief.md") (renderBeliefMd b)


renderBeliefMd :: Belief -> Text
renderBeliefMd b = T.unlines
    [ "# belief.md — black-box findings for `" <> bTaskId b <> "`"
    , ""
    , "**Detected form**: `" <> bbtName (bDetectedType b) <> "`"
    , "**Probes executed**: " <> tshow (bProbeCount b)
    , "**Duration**: " <> T.pack (showFFixed 1 (bDurationSec b)) <> " s"
    , ""
    , "## Identity"
    , maybe "_unknown_" id (bIdentity b)
    , ""
    , "## CLI surface"
    , bulletList (bCliSurface b)
    , ""
    , "## I/O model"
    , maybe "_unknown_" id (bIoModel b)
    , ""
    , "## Exit codes"
    , T.unlines [ "| " <> tshow code <> " | " <> meaning <> " |"
                | (code, meaning) <- bExitCodes b ]
    , ""
    , "## Error message buckets"
    , bulletList (bErrorBuckets b)
    , ""
    , "## Bugs to replicate (bug-as-contract)"
    , bulletList (bBugsToReplica b)
    , ""
    , "## Library fingerprints (guessed)"
    , bulletList (bLibFingerprint b)
    , ""
    , "## Atomic verified facts"
    , bulletList (bProbeFacts b)
    , ""
    , "## Known unknowns"
    , bulletList (bKnownUnknown b)
    , ""
    , "---"
    , ""
    , "_Generated by hs-blackbox-agent v0.1; methodology distill v1._"
    ]
  where
    tshow :: Show a => a -> Text
    tshow = T.pack . show

    bulletList [] = "_(none)_"
    bulletList xs = T.unlines ["- " <> x | x <- xs]

    showFFixed n d =
        let s = show (fromIntegral (round (d * 10 ^ n) :: Integer) / (10 ^ n :: Double))
        in s
